# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180623_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategory',
            old_name='parents_category',
            new_name='parents_category',
        ),
    ]
