# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-19 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190617_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '测试用',
                'verbose_name_plural': '测试用',
            },
        ),
    ]
